// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.leiv.domain;

import java.io.Serializable;
import org.leiv.domain.GeneralPK;

privileged aspect GeneralPK_Roo_Serializable {
    
    declare parents: GeneralPK implements Serializable;
    
    private static final long GeneralPK.serialVersionUID = 1L;
    
}
