// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.leiv.domain;

import org.leiv.domain.General;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect General_Roo_Configurable {
    
    declare @type: General: @Configurable;
    
}
