// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.leiv.domain;

import org.leiv.domain.Work;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Work_Roo_Configurable {
    
    declare @type: Work: @Configurable;
    
}
